### PR TITLE
Automatically refresh gh-page to hashbrown crate doc

### PR DESCRIPTION
**Pull request by lzutao**
@Amanieu ~Could you set project set to https://rust-lang.github.io/hashbrown?~
Could set repository website in GitHub interface to that link?

### CODE REVIEW

**Comment by Amanieu** [comment]
> @Amanieu Could you set project set to https://rust-lang.github.io/hashbrown?

I don't understand, what do you need me to do?

**Comment by lzutao** [comment]
Oh, typo. Could set repository website in GitHub interface to that link?

**Comment by Amanieu** [comment]
The PR is failing in travis:
```
$ echo '<meta http-equiv=refresh content=0;url=hashbrown/index.html>' > target/doc/index.html
/home/travis/.travis/functions: line 104: target/doc/index.html: No such file or directory
```

**Comment by lzutao** [comment]
Forgot to build the crate doc first. Waiting for travis...

**Comment by Amanieu** [comment]
Thanks!

**Pull request merged**
