### PR TITLE
Check in CI that the crate builds on targets without libstd

### LINKED ISSUE #109: hashbrown has a hard time compiling against libcore now
```rust
error[E0599]: no method named `entry` found for type `hashbrown::map::HashMap<rusttype::GlyphId, M>` in the current scope
  --> livesplit-core\src\rendering\glyph_cache.rs:31:21
   |
31 |         self.glyphs.entry(glyph).or_insert_with(|| {
   |                     ^^^^^
   |
   = note: the method `entry` exists but the following trait bounds were not satisfied:
           `hashbrown::map::DefaultHashBuilder : core::hash::BuildHasher`
```

ed0b240192c3a5c5c20995c7f8188453ce4e3a2f still builds. So it's either the raw API or more likely AHash that broke it.

### PR DESCRIPTION
**Pull request by Amanieu**
Fixes #109

### CODE REVIEW

**Comment by Amanieu** [comment]
cc @tkaitchuck: This is blocked on `const_random` adding `#![no_std]`.

**Comment by Amanieu** [comment]
@tkaitchuck It seems that public dependencies (`public = true`) are only supported on nightly.

**Comment by Amanieu** [comment]
Hmm I'm not sure why this worked before though...

**Comment by Amanieu** [comment]
Oh it's because `const-random` 0.1.3 didn't use `public = true`.

**Comment by Amanieu** [comment]
@tkaitchuck Can you please remove `public = true` from the `const-random` crate's Cargo.toml? And check that AHash compiles on stable.

**Comment by tkaitchuck** [comment]
@Amanieu Does this still cause a problem with const-random 0.1.5

**Comment by tkaitchuck** [comment]
Done. Const_random 0.1.6.

**Comment by Amanieu** [comment]
@tkaitchuck `no_panic` seems to be causing build failures on Windows, can you investigate?

**Comment by Amanieu** [comment]
@tkaitchuck Also, `ahash` seems to be importing the `alloc` crate, which is not actually used: https://travis-ci.com/rust-lang/hashbrown/jobs/223101557

**Comment by Amanieu** [comment]
The `no_panic` failure can be reproduced with: 
```
cargo test --target x86_64-pc-windows-gnu --no-run
```
Make sure you have the mingw linker properly set up in ~/.cargo/config

**Comment by tkaitchuck** [comment]
The issue is this: https://github.com/rust-lang/rust/issues/33465
I have confirmed that the work around posted there fixes the issue. I don't have permission to re-open that issue. 
@Amanieu Is this something we can easily work around? If we can't update the config bors uses to do the right thing, or modify the command to pass the flags to do it for this build, I could disable no-panic so that it does not attempt to use a linker. Obviously that is not ideal.

**Comment by tkaitchuck** [comment]
I saw two issues with running that command the first was: 
https://github.com/rust-lang/rust/issues/33465
Which appears to still be an unresolved issue.

But I assume based on your comment about the config that this is not what you are referring to. The second issue was due to the optimizer not being aggressive enough. I've fixed this is 0.2.10. Hopefully that resolves the issue

**Comment by Amanieu** [comment]
@tkaitchuck Windows builds are still failing, I think you need to mark the `#[no_panic]` test with `#[cfg(test)]`.

**Comment by tkaitchuck** [comment]
Ok, done. 
But I am confused, was it building it in the 'dev' profile?

**Comment by Amanieu** [comment]
The builds seem to be fixed now. I'm just waiting on https://github.com/rust-lang/rust/pull/63302 to land on nightly for the thumbv6m fix.

By the way, `no-panic` should be a dev-dependency now so it doesn't get pulled in outside of tests.

**Comment by Amanieu** [comment]
>  But I am confused, was it building it with the 'dev' profile?

The reason it was still failing is because the profile flags in Cargo.toml are only taken into account when building that crate directly. They are ignored when a crate is built as a dependency.

**Pull request merged**
