### PR TITLE
Revert "feat: borsh serde"

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
Reverts rust-lang/hashbrown#525

### CODE REVIEW

**Comment by kayabaNerve** [comment]
This doesn't update the Cargo.toml to remove the borsh feature/dependency from there.

**Comment by dzmitry-lahoda** [comment]
Sorry, will revert. So weird how it happend. I pressed revert in GH on commit which did added both rust and toml changes.

**Comment by Amanieu** [comment]
Can you update this PR to also revert the changes in Cargo.toml?

We will likely release 0.16 after this is merged since this is a breaking change.

**Pull request merged**
