### PR TITLE
Rework the Entry API

### PR DESCRIPTION
**Pull request by Amanieu**
The main change in this PR is that `OccupiedEntry` no longer holds the
key used in the initial `entry` call. As a result, `OccupiedEntryRef` is
no longer required since `OccupiedEntry` can be used in `EntryRef`
directly.

The following methods have been removed:
```rust
// hash_map

impl OccupiedEntry {
    fn replace_entry(self, value: V) -> (K, V);
    fn replace_key(self) -> K;
}

impl EntryRef {
    fn and_replace_entry_with<F>(self, f: F) -> Self;
}

impl VacantEntryRef {
    fn into_key(self) -> K;
}

// hash_set

impl Entry {
    fn replace(self) -> T;
}
```

The following methods have been added:
```rust
impl VacantEntry {
    fn insert_entry(self, value: V) -> OccupiedEntry<'a, K, V, S, A>;
}
```

The following methods have their signatures changed:
```rust
impl EntryRef {
    // Previously returned OccupiedEntryRef
    fn insert(self, value: V) -> OccupiedEntry<'a, K, V, S, A>;
}

impl VacantEntryRef {
    // Previously returned &Q
    fn key(&self) -> &'b Q;

    // Previously returned OccupiedEntryRef
    fn insert(self, value: V) -> OccupiedEntry<'a, K, V, S, A>;
}
```

### CODE REVIEW

**Comment by Amanieu** [comment]
Have you tried using the `entry_ref` API?

**Comment by jwiesler** [comment]
Ah, interesting, didn't know about this one thanks. Is there anything I can read up on why it was done this way? The two APIs seem very similar to me.

**Comment by Amanieu** [comment]
It's a separate API for cases where you want to move the key into the map or make a copy of an existing key without moving it.

**Comment by clarfonthey** [comment]
Currently working on updating `hashbrown` for the standard library, and does the removal of the `replace_entry` API mean that there was the decision to remove it on the Rust side as well? Or was it a mistake to remove it from the `RustcOccupiedEntry`?

**Pull request merged**
