### PR TITLE
Add RawTable#is_full

### PR DESCRIPTION
**Pull request by braddunbar**
There's currently no way to tell  if a particular bucket is full. This can be handy for choosing a random element or iterating over a hash table in a specific order of buckets, so I've added the `is_full` function to RawTable.

### CODE REVIEW

**Comment by braddunbar** [comment]
Ok, so I changed this up so the build is passing and also refactored a bit. Hope you like it!

Also, I'm considering using `is_bucket_full` instead of `is_full` because [`is_empty`](https://docs.rs/hashbrown/0.12.3/hashbrown/raw/struct.RawTable.html#method.is_empty) seems like it's the opposite of `is_full`, but it most certainly is not. Maybe it's only confusing to me though! 🤷‍♀️ 

I would love any feedback on the name, the general idea, or anything else you'd like to talk about! 😺

**Comment by Amanieu** [comment]
I think `is_bucket_full` is a better name, `is_full` might be confused with asking whether the table is full to capacity.

Otherwise I think this is a good addition, but it should be `unsafe` since there is no bounds checking on the bucket index.

**Comment by braddunbar** [comment]
Done and done. Thank you for the feedback @Amanieu!

**Comment by braddunbar** [comment]
Thank you!

**Pull request merged**
